### ISSUE TITLE
Club: issues tracker

### ISSUE THREAD

**Issue by madhusudhand** [Automattic/themes#6374]
## list of issues

- [x] Button hover style and outline button are not working as expected.
![club-buttons](https://user-images.githubusercontent.com/1935113/184134512-8fef506c-8ea3-483f-b695-d8b8c57e251b.gif)

- [x] Post title should reduce one size (right now it has h1 size, design suggests h2 size)
- [ ] Navigation font is matching the designs, but when all pages added it wraps into multiple lines. Should we consider reducing the size a bit?
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1935113/184135079-df494991-7f4d-459f-b667-da30bf70e504.png">

- [x] comments block reply link has double underline
<img width="156" alt="image" src="https://user-images.githubusercontent.com/1935113/184135589-64c03c71-aaab-4ed4-9cef-7b9d394f90ba.png">

- [x] single page -> comments block has title which is redundant I guess. It isn't there in designs, can be removed.
<img width="964" alt="image" src="https://user-images.githubusercontent.com/1935113/184135927-adebf780-df75-4c35-8754-248b1347cddb.png">

- [x] Footer line height are at 1.6, design suggests 1.3
- [x] user and comments font are different
<img width="722" alt="image" src="https://user-images.githubusercontent.com/1935113/184137720-cc609f01-92f6-41c2-aafa-6f5c57f56bdd.png">

**Comment by matiasbenedetto** [comment]
> Navigation font is matching the designs, but when all pages added it wraps into multiple lines. Should we consider reducing the size a bit?

In my opinion, reducing the font size would allow adding more items to the navigation block but it will not avoid the wrapping if the quantity of menu items grows too much. I think we would need @beafialho input here.

**Comment by matiasbenedetto** [comment]
Most of the fixes for these issues are in: https://github.com/Automattic/themes/pull/6366
The fix around the buttons is in: https://github.com/Automattic/themes/pull/6380

**Comment by pbking** [comment]
> In my opinion, reducing the font size will only allows to add more items to the navigation block but it will not avoid the wrapping if the quantity of menu items grows to too much.

I agree with @matiasbenedetto here.  4 or 5 navigation items fit pretty well and is more likely a scenario than what we test with. I don't think we should compromise the design for that unless there's grumbling about it.

**Comment by matiasbenedetto** [comment]
Resolved at https://github.com/Automattic/themes/pull/6366 and https://github.com/Automattic/themes/pull/6380
