### ISSUE TITLE
Task: Delist old versions of updated themes

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#7942]
This task a reminder to delist old versions, and keep track of, themes that received significant updates recently and are being released under new names:

```[tasklist]
### Tasks
- [x] Delist Atrium → Musee
- [x] Delist Curriculum → Launch LeanCV
- [x] Delist Stage → Launch OutNow
- [x] Delist Vetro → Launch Vitrum
- [x] Delist UpsideDown → Launch Inversum
- [x] Delist Cookbook → Launch Recipebook
- [x] Delist Expo → Musee
- [x] Delist The Menu → MyMenu
- [x] Delist Grammer One → Grammer
- [x] Delist Overlaid → Layover
- [x] Delist Blogorama → Brightblog
- [x] Delist DOS → WP-DOS
- [x] Delist Issue → Feature
- [x] Delist Nested → Matrioska
- [x] Delist Ritratto → Retrato
- [x] Delist Screenplay → Moviescript
- [x] Delist Trailblazer > Maverick
- [x] Delist Texty → Titleless
- [x] Delist Raw → Brute
- [x] Delist Programme → Massimo
- [x] Delist Eventual → Happening
- [x] Delist Pieria → Pierian
- [x] Delist Messagerie → Message
- [x] Delist BoxedBio → JazzyGrid
- [x] Delist Organizer → Promoter
```

**Comment by henriqueiamarino** [comment]
@alaczek, we also have themes that must be removed from our repo. They were all committed and submitted to Dotorg under new names.

- Atrium
- Expo
- Trailblazer

**Comment by dsas** [comment]
> @alaczek, we also have themes that must be removed from our repo. They were all committed and submitted to Dotorg under new names.
> 
>     * Atrium
> 
>     * Expo
> 
>     * Trailblazer

https://github.com/Automattic/themes/pull/8069

**Comment by dsas** [comment]
We should double check this delisting list and also see if we need to close or move any issues opened under the old names (they should have a relevant label).

**Comment by iamtakashi** [comment]
LeanCV was launched on dotcom, so feel free to delist the Curriculum when it's ready for dotcom.

**Comment by iamtakashi** [comment]
Vitrum, Inversum, and Outnow were launched on dotcom. Please delist the old versions (Vetro, Stage, and Upsidedown) whenever convenient.

**Comment by iamtakashi** [comment]
MyMenu has launched.

**Comment by iamtakashi** [comment]
Layover has launched.

**Comment by iamtakashi** [comment]
Brightblog has launched.

**Comment by iamtakashi** [comment]
The last items, Grammer and WP-DOS, have launched.

**Comment by alaczek** [comment]
Closing! Thanks @iamtakashi!
